/**
 * Centralized Arabic copy for the restaurant web dashboard (Phase 1C).
 * Internal code uses English enums; display strings live here.
 */

export const ar = {
  shell: {
    modelNote: 'نموذج تشغيلي — بيانات من العينة، بدون حفظ على الخادم',
    restaurantAreaTitle: 'واجهة المطعم',
  },
  role: {
    label: 'الدور التجريبي (واجهة فقط)',
  },
  common: {
    close: 'إغلاق',
    save: 'تطبيق',
    cancel: 'إلغاء',
    back: 'رجوع',
    search: 'بحث',
    filter: 'تصفية',
    empty: 'لا يوجد عناصر مطابقة حالياً',
    all: 'الكل',
    details: 'عرض التفاصيل',
    confirmProto: 'تمت معالجتها في العرض (لا يوجد ربط بخادم).',
  },
  metrics: {
    todayReservations: 'حجوزات اليوم',
    newRequests: 'طلبات جديدة',
    pendingReply: 'بانتظار الرد',
    arrivedGuests: 'زبائن وصلوا',
    seated: 'جالسين',
    noShowRisk: 'احتمال عدم حضور',
    tablesAvailable: 'طاولات متاحة',
    tablesOutOfService: 'طاولات خارج الخدمة',
  },
  dashboard: {
    title: 'تشغيل المطعم',
    todaySection: 'ملخص اليوم',
    byStatus: 'حجوزات اليوم حسب الحالة',
    pendingActions: 'بحاجة إلى إجراء',
    needsAttention: 'تأخير / يحتاج متابعة',
    quickActions: 'إجراءات سريعة',
    quickGoto: 'الانتقال السريع',
    toReservations: 'فتح شاشة الحجوزات',
    toTables: 'إدارة الطاولات',
    toBranches: 'الفروع',
  },
  reservation: {
    listTitle: 'إدارة الحجوزات',
    ref: 'رقم الحجز',
    customer: 'الزبون',
    time: 'الموعد',
    party: 'العدد',
    branch: 'الفرع',
    status: 'الحالة',
    actions: 'الإجراءات',
    filterDate: 'التاريخ',
    filterStatus: 'الحالة',
    filterBranch: 'الفرع',
    filterParty: 'عدد الأشخاص',
    filterSearch: 'بحث بالاسم أو رقم الحجز',
  },
  actions: {
    accept: 'قبول',
    reject: 'رفض',
    proposeOther: 'اقتراح وقت آخر',
    recordArrival: 'تسجيل وصول',
    cancel: 'إلغاء',
    recordSeated: 'تسجيل جلوس',
    complete: 'إكمال الحجز',
    recordNoShow: 'تسجيل عدم حضور',
    viewDetails: 'عرض التفاصيل',
  },
  late: { badge: 'متأخر' },
  panel: {
    title: 'تفاصيل الحجز',
    customerPhone: 'الهاتف',
    table: 'الطاولة',
    internalNotes: 'ملاحظات داخلية (وهمية)',
    actionHistory: 'سجل بسيط (وهمي)',
    timeline: 'مسار الحجز',
  },
  reject: {
    title: 'سبب الرفض',
    r1: 'لا توجد طاولات',
    r2: 'الوقت غير متاح',
    r3: 'العدد غير مناسب',
    r4: 'المطعم مغلق',
    r5: 'مناسبة خاصة',
    r6: 'سبب آخر',
    submit: 'تأكيد الرفض',
  },
  altTime: {
    title: 'اقتراح وقت بديل',
    newTime: 'الوقت المقترح',
    note: 'ملاحظة (اختياري)',
    submit: 'إرسال الاقتراح',
  },
  tables: {
    title: 'الطاولات',
    summary: 'ملخص الحالة',
    list: 'قائمة الطاولات',
    number: 'الرقم',
    capacity: 'السعة',
    zone: 'النوع / المنطقة',
    block: 'حجب الطاولة',
    unblock: 'إرجاعها متاحة',
    outOfService: 'وضع خارج الخدمة',
    clean: 'تنظيف',
  },
  branches: {
    title: 'فروع المطعم',
    phone: 'هاتف الفرع',
    phoneLater: 'يُستكمل عند ربط البيانات',
    resCount: 'حجوزات اليوم (تقريباً)',
    tableCount: 'عدد الطاولات (في العينة)',
    viewRes: 'عرض الحجوزات',
    viewTables: 'عرض الطاولات',
    tempClose: 'إغلاق مؤقت',
    enableBook: 'تفعيل الحجوزات',
    summaryBranchCount: 'عدد الفروع',
    summaryOpenBranches: 'فروع مفتوحة',
    summaryTodayRes: 'الحجوزات اليوم',
    summaryTableCount: 'الطاولات',
    hoursLabel: 'أوقات العمل (نموذج)',
    rowActions: 'إجراءات الفرع',
  },
  branchStatus: {
    open: 'مفتوح',
    closed: 'مغلق',
    temp_closed: 'مغلق مؤقتاً',
    bookings_off: 'الحجوزات معطّلة',
  },
  settings: {
    title: 'إعدادات المطعم (تجريبية)',
    saveProto: 'حفظ (عرضي فقط)',
    acceptBookings: 'قبول الحجوزات',
    allowEdits: 'السماح بتعديل الحجوزات',
    waRemindersLater: 'تفعيل تذكيرات واتساب لاحقاً',
    defaultSession: 'مدة الجلسة الافتراضية',
    defaultSessionUnit: 'دقيقة',
    minutes: 'دقيقة',
    sections: {
      info: 'معلومات المطعم',
      hours: 'أوقات العمل',
      policyBooking: 'سياسة الحجز والإلغاء',
      policy: 'سياسة الإلغاء',
      holdDuration: 'مدة تثبيت الحجز',
      grace: 'فترة السماح للتأخير',
      tablesSessions: 'الطاولات والجلسات',
      seating: 'أنواع الجلسات',
      occasions: 'المناسبات الخاصة',
      notif: 'الإشعارات',
      perms: 'صلاحيات الموظفين',
    },
  },
} as const;

export function rejectReasonLabel(key: string): string {
  const map: Record<string, string> = {
    r1: ar.reject.r1,
    r2: ar.reject.r2,
    r3: ar.reject.r3,
    r4: ar.reject.r4,
    r5: ar.reject.r5,
    r6: ar.reject.r6,
  };
  return map[key] ?? ar.reject.r6;
}
